version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbtest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ncfw
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3302:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./andmebaas.sql:/docker-entrypoint-initdb.d/andmebaas.sql

volumes:
  mariadb_data:
